name: provider
description: Construction Skills and Services Marketplace for Construction Artisans, Building Materials, Master Builders, Real Estate Service

publish_to: 'none'

version: 2.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  nb_utils: 5.0.8-beta.2
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  cached_network_image: ^3.2.3
  google_fonts: ^4.0.3
  html: ^0.15.2
  http: ^0.13.5
  intl: ^0.17.0
  url_launcher: ^6.1.10
  flutter_vector_icons: ^2.0.0
  country_picker: 2.0.19

  #Firebase
  firebase_core: ^2.9.0
  firebase_crashlytics: ^3.1.0
  firebase_remote_config: ^4.0.0
  firebase_auth: ^4.4.0
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.5.0
  firebase_pagination: ^3.0.0

  auto_size_text: 3.0.0
  flutter_custom_tabs: ^1.0.4
  dotted_border: ^2.0.0+3

  #image:
  image_picker: ^0.8.7
  photo_view: ^0.14.0
  file_picker: ^5.2.6
  lottie: ^2.3.2

  # PAYMENTS
  flutter_stripe: ^9.0.0+1
  razorpay_flutter: ^1.3.5
  flutterwave_standard: ^1.0.7
  cinetpay: ^1.0.6
  #  flutter_braintree: ^3.0.0 Remove due to play store does not approving the app

  #notifications:
  onesignal_flutter: 3.4.1
  flutter_typeahead: ^4.3.7

  #chart
  syncfusion_flutter_charts: ^20.4.54

  #map:
  geocoding: ^2.1.0
  flutter_html: ^3.0.0-alpha.3
  flutter_image_stack: ^0.0.6
  android_intent_plus: ^3.1.6

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  # flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  http: ^0.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/
    - assets/icons/
    - assets/lottie/

